<?php
/**
 * Full Page Cache
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * http://opensource.org/licenses/OSL-3.0
 *
 * @package      OSSCube_Fpc
 * @copyright    Copyright (c) 2014 vinay sikarwar
 * @author       Vinay Sikarwar 
 * @license      http://opensource.org/licenses/OSL-3.0 Open Software License (OSL 3.0)
 */
if($url = $this->getAjaxUrl()): ?>
    <script type="text/javascript">
        new Ajax.Request(<?php echo '"' . $url . '"'; ?>);
    </script>
<?php endif;
